import type { Metadata } from "next";
import { Manrope, Markazi_Text } from "next/font/google";
import "./globals.css";

const geistSans = Manrope({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMarkazi = Markazi_Text({
  variable: "--font-geist-markazi",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMarkazi.variable}`}>
        { /* < Header /> */}
        {children}
        {/* < Footer/> */}
      </body>
    </html>
  );
}
